
checkpoint_best:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: val_brier_minFDE6
  filename: best_{epoch}-{val_brier_minFDE6:.2f}-{val_minNLL:.2f}
  save_top_k: 1
  mode: min

checkpoint_last:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  filename: last_{epoch}-{val_brier_minFDE6:.2f}-{val_minNLL:.2f}
  save_last: True

early_stopping: 
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: val_brier_minFDE6
  min_delta: 1e-3
  patience: 10
  mode: "min"
  check_finite: True
  check_on_train_epoch_end: False