completion_callback:
  _target_: nuplan.planning.simulation.main_callback.completion_callback.CompletionCallback
  _convert_: 'all'

  output_dir: ${simulator.output_dir}
  challenge_name: ${simulator.job_name}
