metric_aggregator_callback:
  _target_: nuplan.planning.simulation.main_callback.metric_aggregator_callback.MetricAggregatorCallback
  _convert_: 'all'

  metric_save_path:   ${simulator.output_dir}/${simulator.cl_metric_dir}           # Path of a folder in which the metrics are saved
